Evitar login admin
enbalde-ispc/enbalde-ispc pull request #162
Opened 2024-05-21 01:12 UTC by fmdcba

En el caso de que usuario el usuario que intenta iniciar sesión sea de tipo admin le muestra un mensaje de que no puede loguearse y evita que se actualice la ui

![Captura](https://github.com/enbalde-ispc/enbalde-ispc/assets/95236196/e9d366cb-9643-4f97-ac7d-ca4be04360db)

Closes #157

2024-05-21 03:50 UTC, rpgrca commented
Fijate que mostrás el mensaje en la visual pero lógicamente ya está logueado. Probá loguearte con el admin, que te aparezca el mensaje, y después andá al catálogo y volvé al login, como ya está logueado se transforma en profile.

En lugar de mostrar el mensaje ahí probá tocando el método login en LoginRepository.java, si es Result.Success ahí revisá si es admin, si no es admin que haga lo que hace pero si es admin entonces cambiá result a un Result.Error y agregá ahí que se pueda crear un Error sin excepción sino con un mensaje, poné el mensaje de que no se puede loguear ahí y la visual que quede como estaba para que muestre ese mensaje de error.

2024-05-21 03:51 UTC, rpgrca requested changes
Fijate que mostrás el mensaje en la visual pero lógicamente ya está logueado. Probá loguearte con el admin, que te aparezca el mensaje, y después andá al catálogo y volvé al login, como ya está logueado se transforma en profile.

En lugar de mostrar el mensaje ahí probá tocando el método login en LoginRepository.java, si es Result.Success ahí revisá si es admin, si no es admin que haga lo que hace pero si es admin entonces cambiá result a un Result.Error y agregá ahí que se pueda crear un Error sin excepción sino con un mensaje, poné el mensaje de que no se puede loguear ahí y la visual que quede como estaba para que muestre ese mensaje de error.

2024-05-21 15:18 UTC, fmdcba commented
> Fijate que mostrás el mensaje en la visual pero lógicamente ya está logueado. Probá loguearte con el admin, que te aparezca el mensaje, y después andá al catálogo y volvé al login, como ya está logueado se transforma en profile.
> 
> En lugar de mostrar el mensaje ahí probá tocando el método login en LoginRepository.java, si es Result.Success ahí revisá si es admin, si no es admin que haga lo que hace pero si es admin entonces cambiá result a un Result.Error y agregá ahí que se pueda crear un Error sin excepción sino con un mensaje, poné el mensaje de que no se puede loguear ahí y la visual que quede como estaba para que muestre ese mensaje de error.

Entendido! Llego y hago los cambios

2024-05-22 03:04 UTC, rpgrca commented
Ahí está casi bien, cuando falla loguearse, te vas a otro tab y volvés te vuelve a decir que fallaste como si hubieses presionado el botón otra vez. Eso por ahí se podría quitar para el futuro pero la funcionalidad está andando

2024-05-22 03:05 UTC, merged